"""
11b_larswg_to_bc.py
====================
Builds station-scale daily projections (2021-2100) for the four GCMs available
in the LARS-WG 8 scenario library (CanESM5, GFDL-ESM4, MRI-ESM2-0, UKESM1-0-LL)
directly from LARS-WG 8 stochastic output.

Method (revised)
----------------
LARS-WG 8 is itself the statistical downscaling step: its generator is
calibrated on the observed station record (the .wgx site parameters), and each
future period is produced by perturbing that observed-calibrated generator with
the GCM-derived monthly change factors. The raw LARS-WG output is therefore
ALREADY anchored to the observed climatology and already carries the projected
climate-change signal. Applying a second quantile-mapping against the observed
baseline would re-map the projected distribution back onto the historical one
and thereby remove part of the change signal (in particular the near-term
2021-2040 warming). Accordingly, NO additional bias correction is applied here:
the LARS-WG output is mapped to Gregorian dates, quality-controlled, and written
out directly. (Direct DQM is applied only to IPSL-CM6A-LR and MPI-ESM1-2-HR,
which are absent from the LARS-WG library — see 11_bias_correction_dqm.py.)

LARS-WG output format (whitespace-separated, no header):
  col0: simulated-year number (1..N)
  col1: day-of-year (1-365)
  col2: Tmin (deg C)
  col3: Tmax (deg C)
  col4: Precipitation (mm/day)

Strategy:
  - Each period file (e.g. 2021-2040) contains N>=20 synthetic years;
    the first 20 are mapped to the 20 calendar years of the period.
  - Concatenate 2021-2040 + 2041-2060 + 2061-2080 + 2081-2100 -> 2021-2100.
  - Quality control: precipitation >= 0; enforce Tmax >= Tmin.
  - Write outputs/bias_corrected/{station}_{model}_{scenario}_bc.csv
    (columns bc_tmax, bc_tmin, bc_pr) so downstream scripts are unchanged.
  - Write a validation table comparing the LARS-WG output climatology with the
    observed 2000-2014 climatology (the offset is the expected change signal).

Assumptions:
  - LARS-WG .wgx site parameters were calibrated on the 2000-2020 observed
    record for each station (verified: Sitebase/*.wgx present).
  - A 365-day LARS calendar is mapped to Gregorian by day-of-year; the 29 Feb /
    day 366 is not generated by LARS-WG, so no leap-day handling is required.
"""

import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

warnings.filterwarnings("ignore")

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR   = Path(__file__).resolve().parent.parent
LARS_OUT   = BASE_DIR / "LARS weather generator 8" / "Output"
OBS_EXCEL  = BASE_DIR / "ClimateData_GapFilled_2000_2020.xlsx"
BC_DIR     = BASE_DIR / "outputs" / "bias_corrected"
VAL_DIR    = BC_DIR / "validation_plots"
BC_DIR.mkdir(parents=True, exist_ok=True)
VAL_DIR.mkdir(parents=True, exist_ok=True)

LARS_MODELS = ["CanESM5", "GFDL-ESM4", "MRI-ESM2-0", "UKESM1-0-LL"]
SCENARIOS   = ["ssp245", "ssp585"]
STATIONS    = ["Amol", "Gharakhil", "Sari"]

PERIODS     = ["2021-2040", "2041-2060", "2061-2080", "2081-2100"]
CALIB_START = "2000-01-01"
CALIB_END   = "2014-12-31"

STATION_EXCEL_MAP = {
    "Amol":      "Amol",
    "Gharakhil": "Gharakhil",
    "Sari":      "Sari (Dasht-E-Naz Airport)",
}


# ── Parse LARS-WG .dat file ───────────────────────────────────────────────────
def parse_larswg_dat(filepath: Path, period_str: str) -> pd.DataFrame:
    """
    Parse a LARS-WG 8 output .dat file and return a daily DataFrame with
    Gregorian dates spanning the requested 20-year period.

    Columns (positional): yr_num, doy, tmin, tmax, pr.
    """
    df_raw = pd.read_csv(filepath, sep=r"\s+", header=None, engine="python",
                         names=["yr_num", "doy", "tmin", "tmax", "pr"],
                         usecols=[0, 1, 2, 3, 4]).dropna()

    year_start, year_end = (int(x) for x in period_str.split("-"))
    n_target_years = year_end - year_start + 1               # 20

    use_years = list(range(1, n_target_years + 1))
    subset = df_raw[df_raw["yr_num"].isin(use_years)]

    rows = []
    for sim_yr in use_years:
        greg_yr = year_start + (sim_yr - 1)
        yr_data = subset[subset["yr_num"] == sim_yr]
        for _, row in yr_data.iterrows():
            doy = int(row["doy"])
            date = pd.Timestamp(year=greg_yr, month=1, day=1) + pd.Timedelta(days=doy - 1)
            if date.year != greg_yr:                          # day 366 in a leap year
                date = pd.Timestamp(year=greg_yr, month=12, day=31)
            rows.append({
                "date": date,
                "tmin": float(row["tmin"]),
                "tmax": float(row["tmax"]),
                "pr":   max(0.0, float(row["pr"])),
            })

    df_out = (pd.DataFrame(rows)
              .sort_values("date")
              .drop_duplicates(subset=["date"])
              .set_index("date"))
    return df_out


# ── Load observations (for validation only) ───────────────────────────────────
def load_obs(station_excel_name: str) -> pd.DataFrame:
    df = pd.read_excel(OBS_EXCEL, sheet_name="All_Stations", parse_dates=["date"])
    df = df[df["station_name"] == station_excel_name].copy()
    df = df.set_index("date").sort_index()
    df = df.rename(columns={"tmax": "obs_tmax", "tmin": "obs_tmin", "rrr24": "obs_pr"})
    return df[["obs_tmax", "obs_tmin", "obs_pr"]]


# ── Build the 2021-2100 series directly from LARS-WG output ───────────────────
def build_larswg_series(station: str, model: str, scenario: str) -> pd.DataFrame | None:
    """Concatenate the four period files into a QC'd 2021-2100 daily series."""
    period_dfs = []
    for period in PERIODS:
        fname = f"{station}_{model}[{station},{scenario},{period}]WG.dat"
        fpath = LARS_OUT / fname
        if not fpath.exists():
            print(f"    MISSING: {fpath.name}")
            return None
        period_dfs.append(parse_larswg_dat(fpath, period))

    lars = pd.concat(period_dfs).sort_index()
    lars = lars[~lars.index.duplicated(keep="first")]

    # ── Quality control (no statistical correction) ──────────────────────────
    bc_pr   = np.clip(lars["pr"].values, 0.0, None)
    bc_tmax = lars["tmax"].values.astype(float)
    bc_tmin = lars["tmin"].values.astype(float)
    swap = bc_tmax < bc_tmin                       # enforce physical Tmax >= Tmin
    bc_tmax[swap], bc_tmin[swap] = bc_tmin[swap], bc_tmax[swap]

    return pd.DataFrame({"bc_tmax": bc_tmax, "bc_tmin": bc_tmin, "bc_pr": bc_pr},
                        index=lars.index)


def validate_against_obs(result: pd.DataFrame, obs_df: pd.DataFrame,
                         station: str, model: str, scenario: str) -> dict:
    """
    Compare the 2021-2040 LARS-WG climatology with the observed 2000-2014
    climatology. The difference is the expected near-term change signal, not a
    bias to be removed; this is recorded for transparency.
    """
    near = result.loc["2021-01-01":"2040-12-31"]
    obs  = obs_df.loc[CALIB_START:CALIB_END]
    rec = {
        "station": station, "model": model, "scenario": scenario,
        "obs_Tmax": round(obs["obs_tmax"].mean(), 2),
        "lars2021_2040_Tmax": round(near["bc_tmax"].mean(), 2),
        "dTmax_nearterm": round(near["bc_tmax"].mean() - obs["obs_tmax"].mean(), 2),
        "obs_annPr": round(obs["obs_pr"].resample("YE").sum().mean(), 0),
        "lars_annPr": round(near["bc_pr"].resample("YE").sum().mean(), 0),
    }
    return rec


def main():
    print("=" * 65)
    print("Phase II (LARS-WG track) — direct stochastic downscaling output")
    print("No second quantile mapping (LARS-WG output is already obs-anchored)")
    print("=" * 65)

    total_saved = 0
    validation = []

    for station in STATIONS:
        print(f"\n{'-'*55}\nStation: {station}")
        obs_df = load_obs(STATION_EXCEL_MAP[station])
        print(f"  Obs loaded: {len(obs_df):,} days")

        for model in LARS_MODELS:
            for scenario in SCENARIOS:
                print(f"  Processing: {model} / {scenario} ...", end=" ")
                result = build_larswg_series(station, model, scenario)
                if result is None:
                    print("FAILED")
                    continue
                out_path = BC_DIR / f"{station}_{model}_{scenario}_bc.csv"
                result.to_csv(out_path)
                total_saved += 1
                validation.append(validate_against_obs(result, obs_df,
                                                        station, model, scenario))
                print(f"saved ({len(result):,} days, "
                      f"{result.index[0].date()} to {result.index[-1].date()})")

    print(f"\n{'='*65}\nLARS-WG output files written: {total_saved}")

    if validation:
        vdf = pd.DataFrame(validation)
        vpath = BC_DIR / "larswg_validation_summary.csv"
        vdf.to_csv(vpath, index=False)
        print(f"\nValidation (2021-2040 LARS-WG vs 2000-2014 observed):")
        print(vdf.to_string(index=False))
        print(f"\nSaved: {vpath}")
        print("\nNote: dTmax_nearterm > 0 is the projected near-term warming "
              "signal carried by LARS-WG, NOT a residual bias.")


if __name__ == "__main__":
    main()
